# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-17 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodschannel',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodsspecification',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='skuimage',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='skuspecification',
            old_name='updata_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='specificationoption',
            old_name='updata_time',
            new_name='update_time',
        ),
    ]
